# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='error', max_length=50)),
                ('lasttime', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.URLField(default='error')),
                ('lastid', models.CharField(default='error', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='error', max_length=50)),
                ('imglink', models.URLField(default='error')),
                ('content', models.TextField(default='error')),
            ],
        ),
    ]
